# Generated by Django 5.1 on 2024-08-23 14:12

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='musican',
            old_name='image',
            new_name='musican_image',
        ),
    ]
